blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/navapbc/strata-documentation-engine/discussions
    about: Ask a question or start a conversation that doesn't fit a template.
