"""Build docs/INDEX.md and docs/graph.json deterministically from doc frontmatter."""
import json
import sys
from pathlib import Path

from scripts.lint_docs import load_docs

DEFAULT_DOCS_DIR = "docs"


def build_graph(docs):
    by_id = {d["id"]: d for d in docs}
    nodes = []
    seen_node = set()
    for d in docs:
        if d["id"] in seen_node:
            continue
        seen_node.add(d["id"])
        nodes.append({
            "id": d["id"], "title": d["title"], "source": d["source"],
            "doc_type": d["doc_type"], "tags": sorted(d.get("tags", []) or []),
            "path": d.get("path"),
        })
    sources = sorted({d["source"] for d in docs})
    for s in sources:
        nid = f"source:{s}"
        if nid in seen_node:
            continue
        seen_node.add(nid)
        nodes.append({"id": nid, "title": s, "source": s,
                      "doc_type": "source", "tags": [], "path": None})
    nodes.sort(key=lambda n: n["id"])

    # Index every feature key to the (first) doc that declares it in feature_keys,
    # and every platform component to the (first) doc that declares it in component_keys.
    owners = {}
    component_owners = {}
    for d in docs:
        for k in d.get("feature_keys", []) or []:
            owners.setdefault(k, d["id"])
        for k in d.get("component_keys", []) or []:
            component_owners.setdefault(k, d["id"])

    edges = []
    for s in sources:
        for d in docs:
            if d["source"] == s:
                edges.append({"from": f"source:{s}", "to": d["id"], "rel": "documents"})
    # related -> related-to (same-source free-form links)
    for d in docs:
        for r in d.get("related", []) or []:
            if r in by_id:
                edges.append({"from": d["id"], "to": r, "rel": "related-to"})
    # demonstrates -> example-of, resolved through the feature-key registry
    for d in docs:
        for k in d.get("demonstrates", []) or []:
            owner = owners.get(k)
            if owner and owner != d["id"]:
                edges.append({"from": d["id"], "to": owner, "rel": "example-of"})
            # unowned key -> recorded as a gap (see feature_key_gaps), never a silent edge
    # manages / integrates_with -> manages / integrates-with, via the platform-component registry
    for field, rel in (("manages", "manages"), ("integrates_with", "integrates-with")):
        for d in docs:
            for k in d.get(field, []) or []:
                owner = component_owners.get(k)
                if owner and owner != d["id"]:
                    edges.append({"from": d["id"], "to": owner, "rel": rel})
                # unowned key -> recorded as a gap (see component_key_gaps), never a silent edge

    deduped = []
    seen_edge = set()
    for e in edges:
        key = (e["from"], e["to"], e["rel"])
        if key in seen_edge:
            continue
        seen_edge.add(key)
        deduped.append(e)
    deduped.sort(key=lambda e: (e["from"], e["to"], e["rel"]))
    return {"nodes": nodes, "edges": deduped}


def feature_key_gaps(docs):
    """Registry-valid `demonstrates` keys that no doc's `feature_keys` owns.

    Surfaced (never silent) so a missing SDK feature doc is visible in the report.
    """
    owned = {k for d in docs for k in (d.get("feature_keys") or [])}
    gaps = []
    seen = set()
    for d in docs:
        for k in d.get("demonstrates", []) or []:
            if k not in owned and (d["id"], k) not in seen:
                seen.add((d["id"], k))
                gaps.append({"doc": d["id"], "key": k})
    return sorted(gaps, key=lambda g: (g["doc"], g["key"]))


def component_key_gaps(docs):
    """Registry-valid `manages`/`integrates_with` keys that no doc's `component_keys` owns.

    Surfaced (never silent) so a referenced-but-undocumented component (e.g. an app template
    not yet in the manifest) is visible in the report — the platform-axis analogue of
    `feature_key_gaps`.
    """
    owned = {k for d in docs for k in (d.get("component_keys") or [])}
    gaps = []
    seen = set()
    for d in docs:
        for field in ("manages", "integrates_with"):
            for k in d.get(field, []) or []:
                if k not in owned and (d["id"], k) not in seen:
                    seen.add((d["id"], k))
                    gaps.append({"doc": d["id"], "key": k})
    return sorted(gaps, key=lambda g: (g["doc"], g["key"]))


def render_index(docs):
    lines = ["# Strata Documentation Index", "",
             "> Generated by `scripts/build_graph.py`. Do not edit by hand.", ""]
    by_source = {}
    for d in docs:
        by_source.setdefault(d["source"], []).append(d)
    for source in sorted(by_source):
        lines += [f"## {source}", ""]
        by_type = {}
        for d in by_source[source]:
            by_type.setdefault(d["doc_type"], []).append(d)
        for dt in sorted(by_type):
            lines.append(f"### {dt}")
            for d in sorted(by_type[dt], key=lambda x: x["id"]):
                lines.append(f"- [{d['title']}]({d['path']}) — {d.get('summary', '')}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    docs_dir = Path(DEFAULT_DOCS_DIR)
    docs = load_docs(docs_dir)
    docs_dir.mkdir(parents=True, exist_ok=True)
    (docs_dir / "graph.json").write_text(json.dumps(build_graph(docs), indent=2) + "\n")
    (docs_dir / "INDEX.md").write_text(render_index(docs))
    for gap in feature_key_gaps(docs):
        print(f"GAP: {gap['doc']} demonstrates '{gap['key']}' but no doc owns it")
    for gap in component_key_gaps(docs):
        print(f"GAP: {gap['doc']} references component '{gap['key']}' but no doc owns it")
    print(f"GRAPH_OK {len(docs)} docs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
